### ISSUE TITLE
Multiple Citations Hack not working since commas are removed

### ISSUE THREAD

**Issue by krontzo** [fletcher/MultiMarkdown-6#56]
I tried the hack suggested by Mike Thicke for multiple citations in LaTeX output. 

Given

```
[][#Tversky:1974wi,Kahneman:1979wl,Tversky:1981vc]
```

Expected, as in <http://fletcher.github.io/MultiMarkdown-5/hacking.html>:

```latex
~\citep{Tversky:1974wi,Kahneman:1979wl,Tversky:1981vc}
```
MMD6 result:

```latex
~\citep{tversky:1974wikahneman:1979wltversky:1981vc}
```

In PDF:
```
Bibliography
[1] Tversky:1974wi,Kahneman:1979wl,Tversky:1981vc
```

Using MM6 v 6.0.4. Kudos for the great tool!

**Comment by fletcher** [comment]
Citation behavior is slightly different, and up for additional changes as needed:

https://github.com/fletcher/MultiMarkdown-6/issues/23

I'll add this to the list of things to think about.

Thanks!

**Comment by fletcher** [comment]
Finally had a chance to look at this.

The problem isn't the commas, it's that MMD 6 now allows inline citations (similar to inline footnotes).

Which breaks BibTeX support, since they are all treated as inline citations.

This is now fixed in the development branch for the next release.

**Comment by marcusyoung** [comment]
@fletcher Was this released? As it doesn't seem to work for me, still get the reported behaviour: `~\citep{tversky:1974wikahneman:1979wltversky:1981vc}`
